# by defining spec.containers[].securityContext.allowPrivilegeEscalation: false
# we are preventing the container from gaining more privileges than it was
#  started with.
apiVersion: v1
kind: Pod
metadata:
  name: security-context-pod
spec:
  securityContext:
      runAsUser: 1000
  containers:
  - name: busybox
    image: busybox
    command: [ "sh", "-c", "sleep 3600" ]
    securityContext:
      allowPrivilegeEscalation: false