apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: buffy-sa-watch-rb
  namespace: sunnydale
subjects:
- kind: ServiceAccount
  name: buffy-sa
  namespace: sunnydale
roleref:
  kind: Role
  name: watch-services-secrets
  apiGroup: rbac.authorization.k8s.io