apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: my-psp
spec:
  privileged: false # Don't allow privileged pods!
  # The rest fills in some required fields.
  runAsUser:
    rule: RunAsAny # Allows all user root or non root etc
