# /etc/kubernetes/audit-policy.yml

apiVersion: audit.k8s.io/v1
kind: Policy
rules:
# Log changes to Namespace at the RequestResponse level.
- level: RequestResponse
  resources:
  - group: ""
    resources: ["namespaces"]
# Log pod changes in the audit-test Namespace at Request level
- level: Request
  resources:
  - group: ""
    resources: ["pods"]
  namespaces: ["audit-test"]
# Log all ConfigMap and Secret changes at the Metadata level.
- level: Metadata
  resources:
  - group: ""
    resources: ["configmaps", "secrets"]
# Catch all - log all requests at the Metadata level.
- level: Metadata
