apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: psp-nonpriv # Means privilege mode is set to false
spec:
  privileged: false # Don't allow privileged pods!
  runAsUser:
    rule: RunAsAny # Allows all user root or non root etc
  fsGroup:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - configMap
  - downloadAPI
  - emptyDir
  - persistentVolumeClaim
  - secret
  - projected