apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  annotations:
    container.apparmor.security.beta.kubernetes.io/nginx: localhost/docker-default
spec:
  containers:
  - name: nginx
    image: nginx:stable
