apiVersion: v1
kind: Pod
metadata:
  name: apparmor-disk-write
  annotations:
    container.apparmor.security.beta.kubernetes.io/busybox: localhost/deny-write
spec:
  containers:
  - name: busybox
    image: radial/busyboxplus:curl
    command: ['sh', '-c', 'while true; do echo "I will write to disk!" > diskwrite.log; sleep 5; done']