apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  namespace: nptest
  labels:
    app: client
spec:
  containers:
  - name: client
    image: radial/busyboxplus:curl
    command: ['sh', '-c', 'while true; do curl -m 3 192.168.194.67; sleep 5; done']
