# We can also pass Secret data to a Pod's container in the form of mounted volume. Each
# top-level key in the Secret data will appear to the container process as a file on the
# file system.

# volumes - Define a k8s volume which refrences the Secret with secret.secretName.

# containers.volumeMounts - Mount the volume into the container at a specific path.

apiVersion: v1
kind: Pod
metadata:
  name: secret-volume-pod
spec:
  containers:
  - name: busybox
    image: busybox
    volumeMounts:
    - name: credentials
      mountPath: /etc/credentials
      readOnly: true
  volumes:
  - name: credentials
    secret:
      secretName: my-secret