apiVersion: v1
kind: Pod
metadata:
  name: pod-env-secret
spec:
  restartPolicy: Never
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'echo "The credentials are $SECRET_USERNAME:$SECRET_PASSWORD"']
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: username
    - name: SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: password