apiVersion: v1
kind: Pod
metadata:
  name: pod-volume-secret
spec:
  restartPolicy: Never
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'cat /etc/credentials/username && cat /etc/credentials/password']
    volumeMounts:
    - name: credentials
      mountPath: /etc/credentials
      readOnly: true
  volumes:
  - name: credentials
    secret:
      secretName: my-secret
